### PR TITLE
Derive ApiException to create a specific rate limit exception

### PR DESCRIPTION
**Pull request by Itamaram**
The current tools available to the sdk consumers to handle rate limit exceptions are subpar, as noted previously by others for example [here](https://github.com/XeroAPI/Xero-NetStandard/issues/183) and more recently [here](https://github.com/XeroAPI/Xero-NetStandard/issues/359).

The calling site must be wrapped in a try catch block, handle the case in which an `ApiException` is thrown, and then run a regex on the message to extract relevant information, which doesn't include the critical `Retry-After` header value.

This PR creates a new exception type: `RateLimitException`, which gets thrown in the case when a rate limit error is encountered. It can be handled explicitly and most importantly exposes the delay needed by the caller before making more calls.

This change is fully backwards compatible, as existing code which handles only `ApiException`s will still catch the new exception, whose message is set to be identical to its base class, hence the change is not breaking.

### CODE REVIEW

**Comment by TheosNz** [comment]
Hi there, is there an ETA on this issue being fixed and merged? Currently we are attempting to use the SDK to meet the best practice described in the API limit documentation but am unable to access the Retry-After header through the current version of the SDK. I can see that this fix will respect what the API limit describes should be available. This has been open for 5 months and the SDK still is not providing what is available in the headers and we do not want to apply our own work around as we want to keep the supporting libraries up to date rather than custom.

**Comment by RettBehrens** [comment]
@Itamaram @TheosNz Will something like [this](https://github.com/XeroAPI/Xero-NetStandard/pull/408) work? I've tested it locally after modifying our upstream code generator mustache templates.

Apologies for the delay on this. There were significant changes for the team last year and we're looking to ramp up velocity this year now that we're back to full headcount.

**Comment by Itamaram** [comment]
Looks good to me. As long as it allows the user to know they can/need to retry, and how long to wait before doing so.

If I may nitpick though, I would strongly recommend `RetryAfter` to be made a nullable int, as it would be used as an indicator as to whether or not the request was rate limited.

**Comment by RettBehrens** [comment]
I've updated so `RetryAfter` is a nullable int. Want to give it one more quick glance before I merge and release fix?

**Comment by Itamaram** [comment]
Hey @RettBehrens, apologies, I thought this was a draft PR, so I didn't provide a full review. Seeing how I can't actually leave comments on your PR, I've create a PR into you PR so that I may annotate it. You can find it here: https://github.com/XeroAPI/Xero-NetStandard/pull/410#pullrequestreview-875368319

There are a couple of missing comments, and a style suggestion, and most importantly, a change to ensure full backwards compatibility, that you've lost when changing the error message.

**Comment by RettBehrens** [comment]
Thank you for providing feedback. I have incorporated these changes [here](https://github.com/XeroAPI/Xero-NetStandard/pull/408). If all looks good. Give me a thumbs up and I'll get it released. Thanks again!

**Comment by Itamaram** [comment]
I have to ask, is there a reason why you did not merge my PR into yours, and instead copy pasted the code across?
It's coming across to me as an attempt to explicitly avoid giving me credit for my work, which I would say is somewhat of an impolite practice in general, and even more so in an open source project.

**Comment by RettBehrens** [comment]
No, sorry. I apologize it's coming across that way. It's because these files are generated via mustache templates in our codegen repo and I must make the changes upstream and regenerate the SDK. I would very much like to credit you for the work and can shout out in the release as well as send you some developer swag if you like but can't merge the PR given the workflow for generating our SDKs.

**Comment by RettBehrens** [comment]
https://github.com/XeroAPI/Xero-NetStandard#contributing

**Comment by Itamaram** [comment]
Right that makes sense, I didn't realise that was the case.

Yes, the other PR looks good to me. And I would definitely love me a shout out and some swag :)

**Comment by RettBehrens** [comment]
Resolved with the latest release [3.22.1](https://github.com/XeroAPI/Xero-NetStandard/releases/tag/3.22.1)

**Pull request closed without merging**
