### PR TITLE
Remove ITokenStore (non-async)

### PR DESCRIPTION
**Pull request by MJMortimer**

### CODE REVIEW

**Comment by MJMortimer** [comment]
@Quppa I think having your changes in this are better than the dual async/non-async code paths we had in the other branch. Is there more work you'd like to do in here or is this complete?

**Comment by Quppa** [comment]
I just pushed a few more async/await tweaks - hope that's okay.

Should `AuthorizeUser` in `TokenStoreAuthenticatorBase` also be made async-capable? What sort of implementations can there be?

**Comment by MJMortimer** [comment]
Currently the only way to authorize a user is by redirecting the user to app.xero.com and having them an org to auth into

**Comment by Quppa** [comment]
Seems like there's no reason to make that method async, then. I think the PR is complete, then.

**Pull request merged**
