### PR TITLE
fix: added missing invoice type and currency code enums

### PR DESCRIPTION
**Pull request by ThirstyJarek**
The Xero API returns enum values that have not been included in the OAuth2 SDK. This was causing certain API calls to fail at deserialising the returned data into the correct objects, resulting in the Xero object being set as null. The following API calls were affected:
- GetAccountsAsync()
- GetPaymentsAsync()

Adding these missing enums in appears to have fixed most of the issues we've encountered so far, but there are likely to be more missing enums. 

Also there's probably a better value to set for the empty currency code enum, that value was just used to get it working

### CODE REVIEW

**Comment by ThirstyJarek** [comment]
I can see that you've [updated the Open API Spec](https://github.com/XeroAPI/Xero-OpenAPI/pull/120/commits/5a341b1ba125ff38acefb927e177eea63144ac62) to include the missing Invoice Type Enums, so the next time the C# SDK is generated from the spec these should be fixed. 

However, there's still the issue caused by the empty currency code on accounts.

**Comment by SidneyAllen** [comment]
@ThirstyJarek  you said "still the issue caused by the empty currency code on accounts."

I can see ZWD is in our OpenAPI specs, but I'm confused by your addition of NA.

Can you explain the circumstances where a currency code would be NULL or empty string?

**Comment by ThirstyJarek** [comment]
@SidneyAllen You can ignore the ZWD line, it's only showing up as changed due to the comma. I'm not entirely sure how the account was inserted into Xero with an empty currency code, but that is what's being returned by the API and we were able to resolve that by putting that empty enum value in. I have a [support case here](https://central.xero.com/s/case?caseId=5003m00000zpS9xAAE) that notes a tenant guid and account guid for an account that was originally getting this error.

**Comment by SidneyAllen** [comment]
@ThirstyJarek - what method are you calling?  createInvoice? createAccount?

I'd like to understand under what circumstances you are experiencing this issue.

**Comment by ThirstyJarek** [comment]
@SidneyAllen I'm calling GetAccountsAsync() for hundreds of different organisations. I'd say at least two of these organisations had this issue where an empty string/null was returned for the currency code. 

Just to clarify I didn't create these accounts via the API, i'm simply trying to retrieve them, so these accounts were created through some other means I'm unaware of.

**Comment by SidneyAllen** [comment]
@ThirstyJarek - we will be addressing this in the next update of our OpenAPi Specs and generating updated Models for that reason we won't be accepting your PR - but appreciate the feedback on this issue so it could be solved in the Spec.

**Comment by ThirstyJarek** [comment]
@SidneyAllen No worries Sidney!

**Pull request closed without merging**
